version: 2
jobs:
  debloy:
    docker:
      - image: circleci/node:9.10
    steps:
      - run:
          name: Update package listing & install python-dev and python-pip
          command: sudo apt-get update && sudo apt-get install python-dev python-pip
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - checkout
      - run:
          name: "Run deploy script"
          command: './publish.sh'
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
