version: 2.1
jobs:
  deploy:
    docker:
      - image: cimg/node:18.15.0
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: 'npm install'
      - run:
          name: "Build CRA"
          command: 'npm run build'
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control 'max-age=1200'
          from: build
          to: 's3://potentiaali/'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
orbs:
  aws-s3: circleci/aws-s3@3.1.1
