version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:10.1
    steps:
      - run:
          name: Fix circleci issue with jessie-update binary list on 20180326
          command: |
            sudo cat /dev/null > /etc/apt/sources.list
            echo "deb http://archive.debian.org/debian/ jessie main" | sudo tee -a /etc/apt/sources.list
            sudo apt-get update
      - run:
          name: Istall python-dev and python-pip
          command: sudo apt-get install python-dev python-pip
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - checkout
      - run:
          name: "Run deploy script"
          command: './publish.sh'
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
