version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.10
    steps:
      - run:
          name: Update package listing
          command: sudo apt-get update
      - run:
          name: Install python-dev
          command: sudo apt-get install python-dev
      - run:
          name: Install pip
          command: sudo apt-get install python-pip
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - checkout
      - run:
          name: "Run deploy script"
          command: './publish.sh'
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
