version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.10
      - image: circleci/python:2.7-jessie
    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - checkout
      - run:
          name: "Run deploy script"
          command: './publish.sh'
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
